POST http://localhost:5125/userwords
Content-Type: application/json

{
    "UserId": "67ed7be6-07f6-462a-95e5-d53108d7d5d3",
    "WordValue": "Serendipity"
}



###
GET http://localhost:5125/userwords/67ed7be6-07f6-462a-95e5-d53108d7d5d3

