POST http://localhost:5125/auth/register
Content-Type: application/json

{
    "Email": "testuser@example.com",
    "Password": "Password123!",
    "ConfirmPassword": "Password123!",
    "FirstName": "John",
    "LastName": "Doe"
}
