// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using upword.Api.Data;

#nullable disable

namespace upword.Api.Data.Migrations
{
    [DbContext(typeof(upwordContext))]
    [Migration("20240711205721_SeedWords")]
    partial class SeedWords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("upword.Api.Entities.Word", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Definition")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExampleSentence")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartOfSpeech")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pronunciation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            DateAdded = new DateOnly(2024, 7, 11),
                            Definition = "The occurrence and development of events by chance in a happy or beneficial way.",
                            ExampleSentence = "The discovery of penicillin was a serendipity.",
                            PartOfSpeech = "Noun",
                            Pronunciation = "/ˌserənˈdipədē/",
                            Value = "Serendipity"
                        },
                        new
                        {
                            Id = "2",
                            DateAdded = new DateOnly(2024, 7, 11),
                            Definition = "Lasting for a very short time.",
                            ExampleSentence = "The beauty of cherry blossoms is ephemeral, lasting only a few days.",
                            PartOfSpeech = "Adjective",
                            Pronunciation = "/əˈfem(ə)rəl/",
                            Value = "Ephemeral"
                        },
                        new
                        {
                            Id = "3",
                            DateAdded = new DateOnly(2024, 7, 11),
                            Definition = "Present, appearing, or found everywhere.",
                            ExampleSentence = "In the modern world, smartphones have become ubiquitous.",
                            PartOfSpeech = "Adjective",
                            Pronunciation = "/yo͞oˈbikwədəs/",
                            Value = "Ubiquitous"
                        },
                        new
                        {
                            Id = "4",
                            DateAdded = new DateOnly(2024, 7, 11),
                            Definition = "Fluent or persuasive in speaking or writing.",
                            ExampleSentence = "Her eloquent speech moved the entire audience.",
                            PartOfSpeech = "Adjective",
                            Pronunciation = "/ˈeləkwənt/",
                            Value = "Eloquent"
                        },
                        new
                        {
                            Id = "5",
                            DateAdded = new DateOnly(2024, 7, 11),
                            Definition = "Persistence in doing something despite difficulty or delay in achieving success.",
                            ExampleSentence = "His perseverance in the face of adversity was truly inspiring.",
                            PartOfSpeech = "Noun",
                            Pronunciation = "/ˌpərsəˈvirəns/",
                            Value = "Perseverance"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
